language: node_js
node_js:
  - "8"
dist: trusty
sudo: false
branches:
  only:
    - master
    - dev
addons:
  chrome: stable # have Travis install chrome stable.
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm i
script:
  - npm run lib && npm run build
